//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_Writer {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recipe_Writer.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new ingredient to the database.
        /// </summary>
        internal static string AddNewIngredientToBase {
            get {
                return ResourceManager.GetString("AddNewIngredientToBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new ingredient to this recipe.
        /// </summary>
        internal static string AddNewIngredientToRecipe {
            get {
                return ResourceManager.GetString("AddNewIngredientToRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new instruction to this recipe.
        /// </summary>
        internal static string AddNewInstructionToThisRecipe {
            get {
                return ResourceManager.GetString("AddNewInstructionToThisRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application language.
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The base will be rebuilt..
        /// </summary>
        internal static string BaseWillBeRebuilt {
            get {
                return ResourceManager.GetString("BaseWillBeRebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Completion time :.
        /// </summary>
        internal static string CompletionTime {
            get {
                return ResourceManager.GetString("CompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Really delete the displayed recipe?.
        /// </summary>
        internal static string ConfirmDeleteDisplayedRecipeFromDB {
            get {
                return ResourceManager.GetString("ConfirmDeleteDisplayedRecipeFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove this ingredient definitely ?.
        /// </summary>
        internal static string ConfirmDeleteIngredientFromDB {
            get {
                return ResourceManager.GetString("ConfirmDeleteIngredientFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Really delete the instruction ?.
        /// </summary>
        internal static string ConfirmDeleteInstruction {
            get {
                return ResourceManager.GetString("ConfirmDeleteInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep the old image file ?.
        /// </summary>
        internal static string ConfirmKeepOldImageFile {
            get {
                return ResourceManager.GetString("ConfirmKeepOldImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database file not found..
        /// </summary>
        internal static string DBfileNotFound {
            get {
                return ResourceManager.GetString("DBfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database will be built with the initial data..
        /// </summary>
        internal static string DBWillBeBuiltWithInitialData {
            get {
                return ResourceManager.GetString("DBWillBeBuiltWithInitialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deduction from inventory.
        /// </summary>
        internal static string DeductionFromInventory {
            get {
                return ResourceManager.GetString("DeductionFromInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit ingredient name.
        /// </summary>
        internal static string EditIngredientName {
            get {
                return ResourceManager.GetString("EditIngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit basic information for this recipe.
        /// </summary>
        internal static string EditRecipeBasicInfo {
            get {
                return ResourceManager.GetString("EditRecipeBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter basic information for the new recipe.
        /// </summary>
        internal static string EnterBasicInfoForNewRecipe {
            get {
                return ResourceManager.GetString("EnterBasicInfoForNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name for the illustration image :.
        /// </summary>
        internal static string EnterNameForIllustrationImage {
            get {
                return ResourceManager.GetString("EnterNameForIllustrationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database is corrupted..
        /// </summary>
        internal static string ErrorDatabaseCorrupted {
            get {
                return ResourceManager.GetString("ErrorDatabaseCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill in all fields..
        /// </summary>
        internal static string ErrorEmptyFields {
            get {
                return ResourceManager.GetString("ErrorEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during export : {0}.
        /// </summary>
        internal static string ErrorExport {
            get {
                return ResourceManager.GetString("ErrorExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while adding ingredient : {0}.
        /// </summary>
        internal static string ErrorIngredientAdd {
            get {
                return ResourceManager.GetString("ErrorIngredientAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error inserting an ingredient : {0}.
        /// </summary>
        internal static string ErrorIngredientInsert {
            get {
                return ResourceManager.GetString("ErrorIngredientInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum number of ingredients for the recipe reached..
        /// </summary>
        internal static string ErrorMaxIngredientsNbReached {
            get {
                return ResourceManager.GetString("ErrorMaxIngredientsNbReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a completion time for the recipe..
        /// </summary>
        internal static string ErrorMustEnterACompletionTime {
            get {
                return ResourceManager.GetString("ErrorMustEnterACompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a title for the recipe.
        /// </summary>
        internal static string ErrorMustEnterATitle {
            get {
                return ResourceManager.GetString("ErrorMustEnterATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a title for the new recipe..
        /// </summary>
        internal static string ErrorMustEnterATitleForNewRecipe {
            get {
                return ResourceManager.GetString("ErrorMustEnterATitleForNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter at least one ingredient..
        /// </summary>
        internal static string ErrorMustEnterAtLeastOneIngredient {
            get {
                return ResourceManager.GetString("ErrorMustEnterAtLeastOneIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid number for the time of completion of the recipe.
        /// </summary>
        internal static string ErrorMustEnterValidNumberForTimeCompletion {
            get {
                return ResourceManager.GetString("ErrorMustEnterValidNumberForTimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please use only letters from A to Z without accents, hyphens, underscores or numbers for the file name..
        /// </summary>
        internal static string ErrorMustUseOnlyLettersForTheFileName {
            get {
                return ResourceManager.GetString("ErrorMustUseOnlyLettersForTheFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No ingredient was selected.
        /// </summary>
        internal static string ErrorNoIngredientSelected {
            get {
                return ResourceManager.GetString("ErrorNoIngredientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid actual number for the quantity of the ingredient..
        /// </summary>
        internal static string ErrorNotANumber {
            get {
                return ResourceManager.GetString("ErrorNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web pages|*.html;*.htm.
        /// </summary>
        internal static string ExportToHTMLDialogFilter {
            get {
                return ResourceManager.GetString("ExportToHTMLDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export the recipe to a web page..
        /// </summary>
        internal static string ExportToHTMLDialogTitle {
            get {
                return ResourceManager.GetString("ExportToHTMLDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag and drop a recipe title into the box of your choice, or select its title and double-click on an empty box to assign it..
        /// </summary>
        internal static string HowToUsePlannerText {
            get {
                return ResourceManager.GetString("HowToUsePlannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name to give the image :.
        /// </summary>
        internal static string ImageFilename {
            get {
                return ResourceManager.GetString("ImageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount of ingredients needed to make this recipe has been deducted..
        /// </summary>
        internal static string InfoAmountOfIngredientsNeededDeducted {
            get {
                return ResourceManager.GetString("InfoAmountOfIngredientsNeededDeducted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingredient successfully deleted from the database..
        /// </summary>
        internal static string InfoIngredientDeletedFromDB {
            get {
                return ResourceManager.GetString("InfoIngredientDeletedFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The recipe has been successfully exported !.
        /// </summary>
        internal static string InfoRecipeExported {
            get {
                return ResourceManager.GetString("InfoRecipeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of.
        /// </summary>
        internal static string IngredientConnector {
            get {
                return ResourceManager.GetString("IngredientConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instruction :.
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory of ingredients.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meat.
        /// </summary>
        internal static string lblTypeIngredient1 {
            get {
                return ResourceManager.GetString("lblTypeIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alcohols and spirits.
        /// </summary>
        internal static string lblTypeIngredient11 {
            get {
                return ResourceManager.GetString("lblTypeIngredient11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauces and water.
        /// </summary>
        internal static string lblTypeIngredient12 {
            get {
                return ResourceManager.GetString("lblTypeIngredient12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fish and seafood.
        /// </summary>
        internal static string lblTypeIngredient2 {
            get {
                return ResourceManager.GetString("lblTypeIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fruit.
        /// </summary>
        internal static string lblTypeIngredient3 {
            get {
                return ResourceManager.GetString("lblTypeIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vegetables, legumes and mushrooms.
        /// </summary>
        internal static string lblTypeIngredient4 {
            get {
                return ResourceManager.GetString("lblTypeIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created by Laurent Barraud..
        /// </summary>
        internal static string LicenceAuthor {
            get {
                return ResourceManager.GetString("LicenceAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This software uses a SQLite database for data management.
        ///It was developed as part of a project to replace work at the end of an apprenticeship.
        ///It is licensed to you under the GNU License.
        ///Please contact me for any improvement or bug report..
        /// </summary>
        internal static string LicenceInfo {
            get {
                return ResourceManager.GetString("LicenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à v.1.1.4 - April 2026.
        /// </summary>
        internal static string LicenceVersion {
            get {
                return ResourceManager.GetString("LicenceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Low budget.
        /// </summary>
        internal static string LowBudget {
            get {
                return ResourceManager.GetString("LowBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meal planner.
        /// </summary>
        internal static string MealPlanner {
            get {
                return ResourceManager.GetString("MealPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of ingredients stored :.
        /// </summary>
        internal static string NbOfIngredientsStored {
            get {
                return ResourceManager.GetString("NbOfIngredientsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Necessary ingredients.
        /// </summary>
        internal static string NecessaryIngredients {
            get {
                return ResourceManager.GetString("NecessaryIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ingredient inserted into base..
        /// </summary>
        internal static string NewIngredientInsertedIntoBase {
            get {
                return ResourceManager.GetString("NewIngredientInsertedIntoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ingredient name :.
        /// </summary>
        internal static string NewIngredientName {
            get {
                return ResourceManager.GetString("NewIngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ingredient name (En) :.
        /// </summary>
        internal static string NewIngredientNameEn {
            get {
                return ResourceManager.GetString("NewIngredientNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ingredient name (Es) :.
        /// </summary>
        internal static string NewIngredientNameEs {
            get {
                return ResourceManager.GetString("NewIngredientNameEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ingredient name (Fr) :.
        /// </summary>
        internal static string NewIngredientNameFr {
            get {
                return ResourceManager.GetString("NewIngredientNameFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparation : .
        /// </summary>
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity of ingredient needed :.
        /// </summary>
        internal static string QtyIngredientNeeded {
            get {
                return ResourceManager.GetString("QtyIngredientNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Results :.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meat / Fish / Seafood.
        /// </summary>
        internal static string TabInventory_0 {
            get {
                return ResourceManager.GetString("TabInventory_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fruits / Vegetables / Legumes / Mushrooms.
        /// </summary>
        internal static string TabInventory_1 {
            get {
                return ResourceManager.GetString("TabInventory_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dairy Products / Eggs.
        /// </summary>
        internal static string TabInventory_2 {
            get {
                return ResourceManager.GetString("TabInventory_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cereals / Starches.
        /// </summary>
        internal static string TabInventory_3 {
            get {
                return ResourceManager.GetString("TabInventory_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spices / Herbs / Condiments.
        /// </summary>
        internal static string TabInventory_4 {
            get {
                return ResourceManager.GetString("TabInventory_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nuts / Seeds.
        /// </summary>
        internal static string TabInventory_5 {
            get {
                return ResourceManager.GetString("TabInventory_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oils / Fats.
        /// </summary>
        internal static string TabInventory_6 {
            get {
                return ResourceManager.GetString("TabInventory_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bakery / Pastry Products.
        /// </summary>
        internal static string TabInventory_7 {
            get {
                return ResourceManager.GetString("TabInventory_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alcohol / Spirits / Sauces / Water.
        /// </summary>
        internal static string TabInventory_8 {
            get {
                return ResourceManager.GetString("TabInventory_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title :.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add ingredient to this recipe.
        /// </summary>
        internal static string ToolStripMenuItemAddIngredientToThisRecipe {
            get {
                return ResourceManager.GetString("ToolStripMenuItemAddIngredientToThisRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected ingredient from this recipe.
        /// </summary>
        internal static string ToolStripMenuItemDeleteSelectedIngredientFromThisRecipe {
            get {
                return ResourceManager.GetString("ToolStripMenuItemDeleteSelectedIngredientFromThisRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this recipe.
        /// </summary>
        internal static string ToolStripMenuItemDeleteThisRecipe {
            get {
                return ResourceManager.GetString("ToolStripMenuItemDeleteThisRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit recipe basic info.
        /// </summary>
        internal static string ToolStripMenuItemEditBasicInfos {
            get {
                return ResourceManager.GetString("ToolStripMenuItemEditBasicInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export this recipe to a web page.
        /// </summary>
        internal static string ToolStripMenuItemExportThisRecipeToAWebPage {
            get {
                return ResourceManager.GetString("ToolStripMenuItemExportThisRecipeToAWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Friday.
        /// </summary>
        internal static string ToolStripMenuItemFriday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monday.
        /// </summary>
        internal static string ToolStripMenuItemMonday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New recipe.
        /// </summary>
        internal static string ToolStripMenuItemNewRecipe {
            get {
                return ResourceManager.GetString("ToolStripMenuItemNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plan this recipe for.
        /// </summary>
        internal static string ToolStripMenuItemPlanThisRecipeFor {
            get {
                return ResourceManager.GetString("ToolStripMenuItemPlanThisRecipeFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturday.
        /// </summary>
        internal static string ToolStripMenuItemSaturday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunday.
        /// </summary>
        internal static string ToolStripMenuItemSunday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thursday.
        /// </summary>
        internal static string ToolStripMenuItemThursday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuesday.
        /// </summary>
        internal static string ToolStripMenuItemTuesday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wednesday.
        /// </summary>
        internal static string ToolStripMenuItemWednesday {
            get {
                return ResourceManager.GetString("ToolStripMenuItemWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indicates if you have enough ingredients to make the recipe..
        /// </summary>
        internal static string ToolTipRecipeReadyToCookStatusText {
            get {
                return ResourceManager.GetString("ToolTipRecipeReadyToCookStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type :.
        /// </summary>
        internal static string TypeIngredient {
            get {
                return ResourceManager.GetString("TypeIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
