//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_Writer {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recipe_Writer.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The base will be rebuilt..
        /// </summary>
        internal static string BaseWillBeRebuilt {
            get {
                return ResourceManager.GetString("BaseWillBeRebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Really delete the displayed recipe?.
        /// </summary>
        internal static string ConfirmDeleteDisplayedRecipeFromDB {
            get {
                return ResourceManager.GetString("ConfirmDeleteDisplayedRecipeFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove this ingredient definitely ?.
        /// </summary>
        internal static string ConfirmDeleteIngredientFromDB {
            get {
                return ResourceManager.GetString("ConfirmDeleteIngredientFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Really delete the instruction ?.
        /// </summary>
        internal static string ConfirmDeleteInstruction {
            get {
                return ResourceManager.GetString("ConfirmDeleteInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep the old image file ?.
        /// </summary>
        internal static string ConfirmKeepOldImageFile {
            get {
                return ResourceManager.GetString("ConfirmKeepOldImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database file not found..
        /// </summary>
        internal static string DBfileNotFound {
            get {
                return ResourceManager.GetString("DBfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database will be built with the initial data..
        /// </summary>
        internal static string DBWillBeBuiltWithInitialData {
            get {
                return ResourceManager.GetString("DBWillBeBuiltWithInitialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deduction from inventory.
        /// </summary>
        internal static string DeductionFromInventory {
            get {
                return ResourceManager.GetString("DeductionFromInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database is corrupted..
        /// </summary>
        internal static string ErrorDatabaseCorrupted {
            get {
                return ResourceManager.GetString("ErrorDatabaseCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill in all fields..
        /// </summary>
        internal static string ErrorEmptyFields {
            get {
                return ResourceManager.GetString("ErrorEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during export : {0}.
        /// </summary>
        internal static string ErrorExport {
            get {
                return ResourceManager.GetString("ErrorExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while adding ingredient : {0}.
        /// </summary>
        internal static string ErrorIngredientAdd {
            get {
                return ResourceManager.GetString("ErrorIngredientAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error inserting an ingredient : {0}.
        /// </summary>
        internal static string ErrorIngredientInsert {
            get {
                return ResourceManager.GetString("ErrorIngredientInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum number of ingredients for the recipe reached..
        /// </summary>
        internal static string ErrorMaxIngredientsNbReached {
            get {
                return ResourceManager.GetString("ErrorMaxIngredientsNbReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a completion time for the recipe..
        /// </summary>
        internal static string ErrorMustEnterACompletionTime {
            get {
                return ResourceManager.GetString("ErrorMustEnterACompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a title for the recipe.
        /// </summary>
        internal static string ErrorMustEnterATitle {
            get {
                return ResourceManager.GetString("ErrorMustEnterATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a title for the new recipe..
        /// </summary>
        internal static string ErrorMustEnterATitleForNewRecipe {
            get {
                return ResourceManager.GetString("ErrorMustEnterATitleForNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter at least one ingredient..
        /// </summary>
        internal static string ErrorMustEnterAtLeastOneIngredient {
            get {
                return ResourceManager.GetString("ErrorMustEnterAtLeastOneIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid number for the time of completion of the recipe.
        /// </summary>
        internal static string ErrorMustEnterValidNumberForTimeCompletion {
            get {
                return ResourceManager.GetString("ErrorMustEnterValidNumberForTimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please use only letters from A to Z without accents, hyphens, underscores or numbers for the file name..
        /// </summary>
        internal static string ErrorMustUseOnlyLettersForTheFileName {
            get {
                return ResourceManager.GetString("ErrorMustUseOnlyLettersForTheFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No ingredient was selected.
        /// </summary>
        internal static string ErrorNoIngredientSelected {
            get {
                return ResourceManager.GetString("ErrorNoIngredientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid actual number for the quantity of the ingredient..
        /// </summary>
        internal static string ErrorNotANumber {
            get {
                return ResourceManager.GetString("ErrorNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web pages|*.html;*.htm.
        /// </summary>
        internal static string ExportToHTMLDialogFilter {
            get {
                return ResourceManager.GetString("ExportToHTMLDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export the recipe to a web page..
        /// </summary>
        internal static string ExportToHTMLDialogTitle {
            get {
                return ResourceManager.GetString("ExportToHTMLDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount of ingredients needed to make this recipe has been deducted..
        /// </summary>
        internal static string InfoAmountOfIngredientsNeededDeducted {
            get {
                return ResourceManager.GetString("InfoAmountOfIngredientsNeededDeducted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingredient successfully deleted from the database..
        /// </summary>
        internal static string InfoIngredientDeletedFromDB {
            get {
                return ResourceManager.GetString("InfoIngredientDeletedFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The recipe has been successfully exported !.
        /// </summary>
        internal static string InfoRecipeExported {
            get {
                return ResourceManager.GetString("InfoRecipeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of.
        /// </summary>
        internal static string IngredientConnector {
            get {
                return ResourceManager.GetString("IngredientConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created by Laurent Barraud..
        /// </summary>
        internal static string LicenceAuthor {
            get {
                return ResourceManager.GetString("LicenceAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This software uses a SQLite database for data management.
        ///It was developed as part of a project to replace work at the end of an apprenticeship.
        ///It is licensed to you under the GNU License.
        ///Please contact me for any improvement or bug report..
        /// </summary>
        internal static string LicenceInfo {
            get {
                return ResourceManager.GetString("LicenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à v.1.1.1 - December 2025.
        /// </summary>
        internal static string LicenceVersion {
            get {
                return ResourceManager.GetString("LicenceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Necessary ingredients.
        /// </summary>
        internal static string NecessaryIngredients {
            get {
                return ResourceManager.GetString("NecessaryIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ingredient inserted into base..
        /// </summary>
        internal static string NewIngredientInsertedIntoBase {
            get {
                return ResourceManager.GetString("NewIngredientInsertedIntoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparation : .
        /// </summary>
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Results :.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indicates if you have enough ingredients to make the recipe..
        /// </summary>
        internal static string ToolTipRecipeReadyToCookStatusText {
            get {
                return ResourceManager.GetString("ToolTipRecipeReadyToCookStatusText", resourceCulture);
            }
        }
    }
}
